[package]
name = "mandelbrot-ptrs"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
malachite = { version = "0.5.0", features = ["floats"] }
rayon = "1.10.0"

[profile.release]
debug = true