[package]
name = "mandelbrot-ptrs"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
malachite-float = "0.5.0"
malachite-base = "0.5.0"
rayon = "1.10.0"

[profile.release]
debug = true